baseURL : 'https://streetdogg.in/'
languageCode: en-us
theme: dream
paginate: 10
title: "streetdogg _"
copyright: Piyush Itankar

DefaultContentLanguage: en
hasCJKLanguage: false

languages:
    en:
        languageName: English
        title: "〉streetdogg"
        weight: 1
        params:
            description: Piyush Itankar's Blog!

services:
    # GA Tracking ID
    googleAnalytics:
        id:

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

    footer:
        since: 2015

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 IST

    sidebar:
        subtitle: Notes from the dog world!
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: All Rights Reserved

    comments:
        enabled: false

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site: dstreetdog

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://stack.jimmycai.com/config/menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
        - identifier: about
          name: About
          url: /about
          weight: -10
    social:
        - identifier: linkedin
          name: Linkedin
          url: https://www.linkedin.com/in/streetdogg/
          params:
              icon: linkedin

        - identifier: github
          name: GitHub
          url: https://github.com/streetdogg
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://x.com/dstreetdog
          params:
              icon: brand-twitter

        - identifier: discord
          name: Discord
          url: https://discord.gg/rBPYta98zD
          params:
              icon: discord

        - identifier: Youtube
          name: Youtube
          url: https://youtube.com/@inpyjama
          params:
              icon: youtube

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 1
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
